
FROM golang:1.18

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

WORKDIR /usr/src/app/client
RUN go build
WORKDIR /usr/src/app/client/cache_client
ENV GODEBUG=x509sha1=1

CMD ["go","test","-v"]
