package server

const (
	LEADER = "LEADER"
	FOLLOWER = "FOLLOWER"
	NO_LEADER = -1
	SHUT_DOWN_SIGNAL = true
	PROD_DB = 0
	TEST_DB = 1
	SUCCESS = "OK"
	ELECTION_RUNNING = true
	NO_ELECTION_RUNNING = false
)